# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'kavyawebapp1'
    azureResourceManagerConnection: 'eastus' # Add Azure service connection in your project settings
    subscriptionId: '85808f8e-3070-4df5-8fa2-100d821e3016'
    action: 'Create'
    resourceGroupName: 'kavyawebapp1'
    location: 'eastus'
    templateLocation: 'C:\Users\Quadrant\Desktop\creating webapp.json'
    csmFile: 'path/to/your/arm-template.json'
    csmParametersFile: 'C:\Users\Quadrant\Desktop\creating webapp.json'
    deploymentMode: 'Incremental'
